default:
  server:
    port: 3000
  #spotify: # Sign up and register your "app" here: https://developer.spotify.com/
  #  client_id: your_client_id
  #  client_secret: your_client_secret
  #  redirect_uri: http://raspberrypi.local:3000/api/spotify
  #  refresh_interval: 5000 # ms
  scoreboard:
    refresh_interval: 10000 # ms
development:
  server:
    port: 3001